
[env]
TERM = "xterm-256color"

[window]
# decorations = "None"
decorations = "Full"
# startup_mode = "Fullscreen"
startup_mode = "Maximized"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
padding = { x = 5, y = 3 }

[window.dimensions]
columns = 180
lines = 60

[font]
size = 11

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
args = ["new", "-A", "-s", "main"]
program = "/usr/bin/tmux"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
   { key = "F11", mods = "Control|Shift", action = "ToggleFullscreen" },
   # { key = "F12", mods = "Control|Shift", action = "ToggleMaximized" },
]

[general]
live_config_reload = true

import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]
